# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dv.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'dv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x64v.proto\x12\x02\x64v\"O\n\x08\x44VHeader\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\trouter_id\x18\x02 \x01(\t\x12\x0b\n\x03seq\x18\x03 \x01(\x04\x12\x12\n\nsent_at_ms\x18\x04 \x01(\x04\"9\n\x05Route\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x10\n\x08next_hop\x18\x02 \x01(\t\x12\x0e\n\x06metric\x18\x03 \x01(\r\"D\n\tDVMessage\x12\x1c\n\x06header\x18\x01 \x01(\x0b\x32\x0c.dv.DVHeader\x12\x19\n\x06routes\x18\x02 \x03(\x0b\x32\t.dv.Route\">\n\x10\x43onnParamMessage\x12\x1c\n\x06header\x18\x01 \x01(\x0b\x32\x0c.dv.DVHeader\x12\x0c\n\x04port\x18\x02 \x01(\r\":\n\x0c\x43onnParamAck\x12\x1c\n\x06header\x18\x01 \x01(\x0b\x32\x0c.dv.DVHeader\x12\x0c\n\x04port\x18\x02 \x01(\r\",\n\x0cHelloMessage\x12\x1c\n\x06header\x18\x01 \x01(\x0b\x32\x0c.dv.DVHeaderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DVHEADER']._serialized_start=16
  _globals['_DVHEADER']._serialized_end=95
  _globals['_ROUTE']._serialized_start=97
  _globals['_ROUTE']._serialized_end=154
  _globals['_DVMESSAGE']._serialized_start=156
  _globals['_DVMESSAGE']._serialized_end=224
  _globals['_CONNPARAMMESSAGE']._serialized_start=226
  _globals['_CONNPARAMMESSAGE']._serialized_end=288
  _globals['_CONNPARAMACK']._serialized_start=290
  _globals['_CONNPARAMACK']._serialized_end=348
  _globals['_HELLOMESSAGE']._serialized_start=350
  _globals['_HELLOMESSAGE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
